Fixed github actions file

diff --git a/.github/workflows/chaos-mesh.yaml b/.github/workflows/chaos-mesh.yaml
--- a/.github/workflows/chaos-mesh.yaml
+++ b/.github/workflows/chaos-mesh.yaml
@@ -27,15 +27,19 @@ jobs:
 
       - name: Deploy an application
         run: |
+          kubectl create ns ochacafe
           kubectl apply -f https://raw.githubusercontent.com/shukawam/ochacafe-chaos-engineering/main/kubernetes/wordpress/namespace.yaml
           kubectl apply -f https://raw.githubusercontent.com/shukawam/ochacafe-chaos-engineering/main/kubernetes/wordpress/mysql.yaml
           kubectl apply -f https://raw.githubusercontent.com/shukawam/ochacafe-chaos-engineering/main/kubernetes/wordpress/wordpress.yaml
 
-      - name: Check pods
+      - name: Check pods_1
+        id: expected
         run: |
+          kubectl sleep 10
           kubectl -n chaos-testing get pods -n chaos-testing
-          sleep 5
+          sleep 10
           kubectl -n ochacafe get pods
+          ::set-output name=expected_pod_num=::`kubectl -n ochacafe get pods --field-selector=status.phase=Running --no-headers | wc -l`
 
       - name: Run chaos mesh action
         uses: shukawam/chaos-mesh-action@main
@@ -44,7 +48,15 @@ jobs:
           CFG_BASE64: a2luZDogUG9kQ2hhb3MNCmFwaVZlcnNpb246IGNoYW9zLW1lc2gub3JnL3YxYWxwaGExDQptZXRhZGF0YToNCiAgbmFtZXNwYWNlOiBvY2hhY2FmZQ0KICBuYW1lOiBwb2Qta2lsbA0Kc3BlYzoNCiAgc2VsZWN0b3I6DQogICAgbmFtZXNwYWNlczoNCiAgICAgIC0gb2NoYWNhZmUNCiAgICBsYWJlbFNlbGVjdG9yczoNCiAgICAgIGFwcDogd29yZHByZXNzDQogIG1vZGU6IG9uZQ0KICBhY3Rpb246IHBvZC1raWxsDQogIGdyYWNlUGVyaW9kOiAw
           CHAOS_MESH_VERSION: v2.1.4
 
-      - name: Verification
+      - name: Check pods_2
+        id: actual
         run: |
+          kubectl sleep 10
           echo "Check Kubernetes Self-Healing"
-          kubectl -n ochacafe get po --no-headers | wc -l
+          ::set-outputactual_pod_num=`kubectl -n ochacafe get pods --field-selector=status.phase=Running --no-headers | wc -l`
+
+      - name: Handling
+        if: ${{steps.expected.outputs.expected_pod_num}} == ${{steps.actual.outputs.actual_pod_num}}
+        run: |
+          echo "Failed Chaos Experiment."
+          exit 1
